// Lookup and search over data/catalog.json (generated by scripts/build-catalog.mjs).

import confirmedJson from "../data/app-confirmed.json";
import catalogJson from "../data/catalog.json";

export interface Param {
  name: string;
  /** String, Number, Boolean, Variable, Enum, DynamicEnum, Array, Dictionary, Time Span, Object, Unknown, ... */
  type: string;
  optional?: boolean;
  allowsVariables?: boolean;
  /** Enumeration name for Enum / DynamicEnum params; values live in catalog.enums. */
  enum?: string;
  object?: string;
}

export interface Action {
  name: string;
  library: string;
  title: string;
  description: string;
  params: Param[];
  syntax: string;
  example: string;
  /** The example was rewritten (spellings, JSON form) from the docs' version. */
  exampleAdapted?: boolean;
  doc: string;
  minIOS?: number;
  premium?: boolean;
}

export interface Library {
  import: string;
  title: string;
  app: string;
  actions: number;
}

/**
 * Another spelling of an enum value. `to` is the spelling to write.
 * - internal: the open-source compiler's identifier (`FileExtension`); the app reads the real
 *   value instead, so this fails like `rejected` (inferred from the confirmed case).
 * - rejected: the app reported an error for it (data/app-confirmed.json).
 * - confirmed: the app accepted it.
 * - docs: the docs examples use it; the app hasn't confirmed it.
 */
export interface EnumAlias {
  to: string;
  status: "internal" | "rejected" | "confirmed" | "docs";
}

export interface Catalog {
  generated: string;
  source: string;
  libraries: Library[];
  metadata: { colors: string[]; icons: string[] };
  /** Enum name → the spellings to write (real Shortcuts values, spaces included). */
  enums: Record<string, string[]>;
  enumAliases: Record<string, Record<string, EnumAlias>>;
  actions: Action[];
}

export const catalog = catalogJson as Catalog;

/** How a `{ … }` dictionary value is written. */
export type DictForm = "plain" | "escaped" | "quoted";

interface DictRule {
  accepted: DictForm[];
  rejected: DictForm[];
  example?: string;
  evidence?: string;
}

/** Facts confirmed by building scripts in the Jellycuts app (data/app-confirmed.json). */
export const appConfirmed = confirmedJson as { dictionaryParams: Record<string, DictRule> };

const byName = new Map<string, Action[]>();
const byLowerName = new Map<string, Action[]>();
for (const action of catalog.actions) {
  byName.set(action.name, [...(byName.get(action.name) ?? []), action]);
  const lower = action.name.toLowerCase();
  byLowerName.set(lower, [...(byLowerName.get(lower) ?? []), action]);
}

export const libraryNames = catalog.libraries.map((l) => l.import);

export function findLibrary(name: string): Library | undefined {
  return catalog.libraries.find((l) => l.import === name);
}

/** Exact-name lookup across all libraries (a few names exist in more than one library). */
export function findActions(name: string): Action[] {
  return byName.get(name) ?? [];
}

/** Case-insensitive lookup, used for "did you mean" when only the casing is wrong. */
export function findActionsIgnoringCase(name: string): Action[] {
  return byLowerName.get(name.toLowerCase()) ?? [];
}

export function enumValues(param: Param): string[] | undefined {
  return param.enum ? catalog.enums[param.enum] : undefined;
}

export function enumAlias(param: Param, spelling: string): EnumAlias | undefined {
  return param.enum ? catalog.enumAliases[param.enum]?.[spelling] : undefined;
}

/** Every spelling the catalog knows for an enum parameter, including aliases. */
export function enumSpellings(param: Param): string[] {
  if (!param.enum) return [];
  return [...(catalog.enums[param.enum] ?? []), ...Object.keys(catalog.enumAliases[param.enum] ?? {})];
}

/**
 * The confirmed way to write a Dictionary parameter, from data/app-confirmed.json. Parameters the
 * app hasn't been tested on come back with no accepted or rejected forms and `confirmed: false`.
 */
export function dictionaryRule(action: Action, param: Param): DictRule & { confirmed: boolean } {
  const rule = appConfirmed.dictionaryParams[`${action.library}:${action.name}:${param.name}`];
  return rule ? { ...rule, confirmed: true } : { accepted: [], rejected: [], confirmed: false };
}

/** Rewrites a JSON object into the given form: plain {"a": "b"} or escaped {\"a\": \"b\"}. */
export function writeDict(json: string, form: DictForm): string {
  const plain = json.replace(/\\"/g, '"');
  return form === "escaped" ? plain.replace(/"/g, '\\"') : plain;
}

// ---- Search -----------------------------------------------------------------------------

const STOPWORDS = new Set(
  "a an the to of for and or in on at by with from my me i it is be do does how can get set make create want need into using use".split(" "),
);

/** Everyday words people use → words that appear in Jelly action names/titles. */
const SYNONYMS: Record<string, string[]> = {
  notify: ["notification"],
  notification: ["notification"],
  push: ["notification"],
  remind: ["reminder", "notification"],
  http: ["url", "download", "contents"],
  api: ["url", "download", "contents", "dictionary"],
  request: ["url", "download"],
  fetch: ["url", "download", "contents"],
  web: ["url", "webpage", "safari"],
  website: ["url", "webpage", "safari"],
  json: ["dictionary"],
  say: ["speak"],
  speak: ["speak"],
  voice: ["speak", "dictate"],
  tts: ["speak"],
  dictation: ["dictate"],
  charge: ["battery"],
  wifi: ["wifi"],
  "wi-fi": ["wifi"],
  internet: ["wifi", "network", "url"],
  screen: ["brightness", "screenshot"],
  sound: ["volume", "sound", "audio"],
  song: ["music", "song"],
  play: ["play", "music"],
  picture: ["photo", "image"],
  pic: ["photo", "image"],
  copy: ["clipboard"],
  paste: ["clipboard"],
  today: ["date"],
  now: ["date"],
  time: ["date", "time"],
  schedule: ["calendar", "event"],
  todo: ["reminder"],
  task: ["reminder"],
  sms: ["message"],
  imessage: ["message"],
  text: ["text", "message"],
  mail: ["email"],
  gps: ["location"],
  where: ["location"],
  directions: ["maps", "directions"],
  temperature: ["weather", "conditions"],
  forecast: ["weather", "forecast"],
  rain: ["weather", "conditions"],
  countdown: ["timer"],
  alarm: ["alarm", "timer"],
  dnd: ["dnd"],
  disturb: ["dnd"],
  focus: ["focus", "dnd"],
  dark: ["appearance"],
  light: ["appearance", "flashlight"],
  torch: ["flashlight"],
  save: ["save", "file"],
  folder: ["folder", "file"],
  icloud: ["file"],
  array: ["list"],
  items: ["list", "item"],
  key: ["dictionary", "value"],
  random: ["random"],
  calculate: ["calculate", "math"],
  add: ["calculate", "add"],
  math: ["calculate", "math"],
  translate: ["translate"],
  run: ["run", "shortcut"],
  launch: ["open", "app"],
  link: ["url"],
  haptic: ["vibrate", "haptic"],
  steps: ["health", "sample"],
  workout: ["workout", "health"],
  phone: ["call", "contact"],
  delay: ["wait"],
  sleep: ["wait"],
  pause: ["wait"],
  prompt: ["ask", "input"],
  input: ["ask", "input"],
  pick: ["choose", "select"],
  select: ["choose", "select"],
  menu: ["choose"],
  show: ["show", "result", "quicklook", "alert"],
  display: ["show", "result", "quicklook"],
  print: ["show", "result", "quicklook"],
  log: ["show", "result", "append"],
  output: ["output", "result"],
  uppercase: ["case"],
  lowercase: ["case"],
  regex: ["match", "replace"],
  quit: ["quit", "exit"],
  stop: ["exit", "stop"],
};

const splitWords = (s: string): string[] =>
  s
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1 $2")
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);

const stem = (w: string) => (w.length > 4 && w.endsWith("s") ? w.slice(0, -1) : w);

interface IndexedAction {
  action: Action;
  nameWords: Set<string>;
  titleWords: Set<string>;
  descWords: Set<string>;
}

const index: IndexedAction[] = catalog.actions.map((action) => ({
  action,
  nameWords: new Set(splitWords(action.name).map(stem)),
  titleWords: new Set(splitWords(action.title).map(stem)),
  descWords: new Set(splitWords(action.description).map(stem)),
}));

export interface SearchOptions {
  library?: string;
  limit?: number;
}

export function searchActions(query: string, options: SearchOptions = {}): Action[] {
  const limit = Math.min(Math.max(options.limit ?? 8, 1), 50);
  const pool = options.library ? index.filter((i) => i.action.library.toLowerCase() === options.library!.toLowerCase()) : index;
  const raw = query.trim();
  if (!raw) return pool.slice(0, limit).map((i) => i.action);

  const words = splitWords(raw).filter((w) => !STOPWORDS.has(w));
  const terms = new Map<string, number>(); // term -> weight
  for (const w of words) {
    terms.set(stem(w), Math.max(terms.get(stem(w)) ?? 0, 1));
    for (const s of SYNONYMS[w] ?? []) terms.set(stem(s), Math.max(terms.get(stem(s)) ?? 0, 0.7));
  }
  const compact = raw.replace(/\s+/g, "").toLowerCase();

  const scored = pool.map((entry) => {
    const { action } = entry;
    let score = 0;
    const lowerName = action.name.toLowerCase();
    if (lowerName === compact) score += 100;
    else if (lowerName.startsWith(compact) && compact.length >= 3) score += 25;
    for (const [term, weight] of terms) {
      let s = 0;
      if (entry.nameWords.has(term)) s = 10;
      else if (entry.titleWords.has(term)) s = 8;
      else if ([...entry.nameWords].some((w) => w.startsWith(term) && term.length >= 3)) s = 5;
      else if (entry.descWords.has(term)) s = 3;
      score += s * weight;
    }
    if (score > 0 && action.library === "Shortcuts") score += 2; // built-ins need no extra app
    return { action, score };
  });

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score || a.action.name.localeCompare(b.action.name))
    .slice(0, limit)
    .map((s) => s.action);
}

// ---- Suggestions ------------------------------------------------------------------------

/** Names models commonly invent, mapped to the real Jelly action. */
export const COMMON_MISTAKES: Record<string, string> = {
  showNotification: "sendNotification",
  notification: "sendNotification",
  notify: "sendNotification",
  showAlert: "alert",
  print: "showResult",
  log: "showResult",
  console: "showResult",
  display: "showResult",
  showText: "showResult",
  say: "speakText",
  speak: "speakText",
  getContentsOfURL: "urlContents",
  getURLContents: "urlContents",
  fetch: "urlContents",
  httpRequest: "downloadURL",
  getBatteryLevel: "batteryLevel",
  getClipboardContents: "getClipboard",
  copyToClipboard: "setClipboard",
  sleep: "wait",
  delay: "wait",
  ask: "askForInput",
  prompt: "askForInput",
  input: "askForInput",
  chooseFromList: "choose",
  chooseFromMenu: "choose",
  getCurrentDate: "date",
  currentDate: "date",
  getWeather: "getCurrentConditions",
  getCurrentWeather: "getCurrentConditions",
  getCurrentLocation: "getLocation",
  setVariable: "var (use `var name = value`)",
  getVariable: "the variable name directly",
  openWebsite: "openURL",
  openLink: "openURL",
  runShortcutNamed: "runShortcut",
  stop: "exit",
  stopShortcut: "exit",
  getDictionaryValue: "valueFor",
  getValueForKey: "valueFor",
  setDictionaryValue: "setValue",
  getItem: "getItemFromList",
  vibrateDevice: "vibrate",
  setDoNotDisturb: "setDND",
  setWifi: "setWiFi",
};

function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  const prev = new Array(b.length + 1).fill(0).map((_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    let diag = prev[0];
    prev[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const tmp = prev[j];
      prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diag + (a[i - 1] === b[j - 1] ? 0 : 1));
      diag = tmp;
    }
  }
  return prev[b.length];
}

/** Closest matches among `candidates` for a misspelt `name`. */
export function closest(name: string, candidates: Iterable<string>, max = 3): string[] {
  const lower = name.toLowerCase();
  const scored: { c: string; d: number }[] = [];
  for (const c of candidates) {
    const cl = c.toLowerCase();
    let d = levenshtein(lower, cl);
    if (cl.includes(lower) || lower.includes(cl)) d = Math.min(d, 1 + Math.abs(cl.length - lower.length) / 4);
    const limit = Math.max(2, Math.floor(Math.max(lower.length, cl.length) * 0.34));
    if (d <= limit) scored.push({ c, d });
  }
  return [...new Set(scored.sort((x, y) => x.d - y.d || x.c.localeCompare(y.c)).map((s) => s.c))].slice(0, max);
}

export function suggestActions(name: string, extra: string[] = []): string[] {
  const out: string[] = [];
  const mistake = COMMON_MISTAKES[name] ?? COMMON_MISTAKES[name.charAt(0).toLowerCase() + name.slice(1)];
  if (mistake && mistake !== name) out.push(mistake);
  for (const a of findActionsIgnoringCase(name)) out.push(a.name);
  out.push(...closest(name, [...byName.keys(), ...extra]));
  if (out.length < 3) out.push(...searchActions(splitWords(name).join(" "), { limit: 3 }).map((a) => a.name));
  return [...new Set(out)].filter((n) => n !== name).slice(0, 4);
}

// ---- Formatting -------------------------------------------------------------------------

export function describeType(p: Param): string {
  let t: string;
  if (p.type === "Enum" || p.type === "DynamicEnum") t = `enum ${p.enum}`;
  else if (p.type === "Object") t = `object ${p.object ?? ""}`.trim();
  else if (p.type === "Unknown" || p.type === "Literal") t = "see example";
  else t = p.type;
  const flags = [p.optional ? "optional" : "", p.allowsVariables ? "accepts ${variables}" : ""].filter(Boolean);
  return flags.length ? `${t}, ${flags.join(", ")}` : t;
}


export function formatActionSummary(a: Action): string {
  const params = a.params.length
    ? a.params.map((p) => `${p.name}${p.optional ? "?" : ""}`).join(", ")
    : "no parameters";
  const lib = a.library === "Shortcuts" ? "" : ` [import ${a.library}]`;
  return `- \`${a.name}\` — ${a.title}${lib}: ${a.description.split("\n")[0]} (params: ${params})`;
}

export function formatActionDetail(a: Action): string {
  const lines: string[] = [];
  lines.push(`### ${a.name} — ${a.title}`);
  const needs = [`import ${a.library}`];
  if (a.minIOS) needs.push(`iOS ${a.minIOS}+`);
  if (a.premium) needs.push("Jellycuts Premium");
  lines.push(`Requires: ${needs.join(", ")}`);
  if (a.description) lines.push(a.description);
  if (a.params.length) {
    lines.push("Parameters:");
    for (const p of a.params) {
      let row = `- \`${p.name}\`: ${describeType(p)}`;
      const values = enumValues(p);
      if (values) {
        const shown = values.length > 40 ? [...values.slice(0, 40), `… (${values.length - 40} more)`] : values;
        row += ` — one of: ${shown.join(", ")}`;
        if (p.type === "DynamicEnum") row += " (or a variable)";
        if (values.some((v) => v.includes(" "))) row += ". Write values exactly as listed, spaces included, without quotes";
      }
      if (p.type === "Dictionary") {
        const rule = dictionaryRule(a, p);
        if (rule.confirmed) {
          const form = rule.accepted[0];
          const sample = writeDict(rule.example ?? '{"key": "value"}', form);
          row += ` — write it as \`${p.name}: ${sample}\` (${form === "plain" ? "plain JSON in braces" : "JSON in braces with every quote escaped as \\\""}, no surrounding quotes, no variables inside); confirmed in the Jellycuts app`;
        } else {
          row += " — how the Jellycuts app wants this written isn't confirmed yet";
          if (a.name === "downloadURL") row += "; for a JSON body use `requestType: File, requestVar: <dictionary>` instead (jelly_guide › recipes)";
        }
        if (a.params.some((q) => q.type !== "Dictionary")) row += ". Put `{ … }` values after the other arguments";
      }
      lines.push(row);
    }
  } else {
    lines.push("Parameters: none — call it as `" + a.name + "()`");
  }
  if (a.example) lines.push(a.exampleAdapted ? "Example (adapted from the docs to what the Jellycuts app accepts):" : "Example (from the docs):", "```jelly", a.example, "```");
  lines.push(`Docs: ${a.doc}`);
  return lines.join("\n");
}
